
spring.application.name=PromptIQ
spring.datasource.url=jdbc:postgresql://localhost:5432/agenticai
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
management.endpoints.web.exposure.include=health,info

logging.level.com.PromptIQ=DEBUG
logging.level.org.springframework.security=DEBUG

spring.security.user.name=admin
spring.security.user.password=123456

app.jwt.secret=8MTWXtKdNc3J1iajD0HzmroS5fWLr4XQd5kRZUETuP8
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000